[package]
name = "crypto_cipher_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
lazy_static = "1.5.0"
serde = {version = "1.0.217", features = ["derive"]}
tera = "1.20.0"

